title = "Michael A. Agarenzo"
baseURL = "https://magarenzo.github.io"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/favicon.png"
  description = "Michael A. Agarenzo - Full Stack Software Engineer"
  github = "https://github.com/magarenzo"
  linkedin = "https://linkedin.com/in/magarenzo"
  background_color_class = "bg-near-black"
  recent_posts_number = 3
  body_classes = "system-sans-serif bg-lightest-blue"